# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id_penyakit', models.AutoField(primary_key=True, serialize=False)),
                ('nama_penyakit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id_protein', models.AutoField(primary_key=True, serialize=False)),
                ('kode_protein', models.CharField(max_length=20)),
                ('nama_protein', models.CharField(max_length=100)),
                ('id_penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamu_app.Penyakit')),
            ],
        ),
        migrations.CreateModel(
            name='Senyawa',
            fields=[
                ('id_senyawa', models.AutoField(primary_key=True, serialize=False)),
                ('kode_senyawa', models.CharField(max_length=20)),
                ('nama_senyawa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id_tanaman', models.AutoField(primary_key=True, serialize=False)),
                ('nama_tanaman', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='senyawa',
            name='id_tanaman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamu_app.Tanaman'),
        ),
    ]
