# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanaman',
            name='nama_latin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tanaman',
            name='nama_tanaman',
            field=models.CharField(max_length=20),
        ),
    ]
