# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamu_app', '0002_auto_20160415_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='senyawa',
            name='rumus_molekul',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
