# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamu_app', '0003_senyawa_rumus_molekul'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyakit',
            name='update_oleh',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='penyakit',
            name='update_pada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='protein',
            name='update_oleh',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='protein',
            name='update_pada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='senyawa',
            name='update_oleh',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='senyawa',
            name='update_pada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='update_oleh',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='tanaman',
            name='update_pada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
