# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamu_app', '0004_auto_20160417_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyakit',
            name='update_pada',
        ),
    ]
