# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamu_app', '0005_remove_penyakit_update_pada'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyakit',
            name='update_pada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
